// Generated by uniffi-bindgen-react-native
#include "orbital-signal.h"
#include "generated/orbital_signal.hpp"

namespace orbitalsignal {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeOrbitalSignal::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}