// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "orbital-signal.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "OrbitalSignalSpec.h"

@interface OrbitalSignal : NSObject <NativeOrbitalSignalSpec>
#else
#import <React/RCTBridgeModule.h>

@interface OrbitalSignal : NSObject <RCTBridgeModule>
#endif

@end