use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Nonce};
use zeroize::Zeroizing;

use crate::error::SignalError;

/// Result of AES-256-GCM encryption — ciphertext (encrypted_data || 16-byte auth tag) + IV.
#[derive(Debug, Clone, uniffi::Record)]
pub struct ContentCryptoResult {
    /// Ciphertext bytes: encrypted_data || 16-byte GCM auth tag.
    pub ciphertext: Vec<u8>,
    /// 12-byte IV (nonce) generated by CSPRNG.
    pub iv: Vec<u8>,
}

/// AES-256-GCM encrypt with Additional Authenticated Data.
///
/// - Generates a fresh 12-byte IV via `rand::fill` (ChaCha12 reseeded from OsRng).
/// - Returns `ContentCryptoResult` with ciphertext (encrypted_data || 16-byte auth tag)
///   and the generated IV.
/// - The `aad` parameter binds the ciphertext to a context (e.g., groupId as UTF-8 bytes),
///   preventing cross-context replay.
///
/// # Errors
///
/// - `InvalidKey` if `key` is not exactly 32 bytes.
/// - `InternalError` if encryption fails (should not happen with valid inputs).
#[uniffi::export]
pub fn aes_gcm_encrypt(
    plaintext: Vec<u8>,
    key: Vec<u8>,
    aad: Vec<u8>,
) -> Result<ContentCryptoResult, SignalError> {
    let key = Zeroizing::new(key);
    if key.len() != 32 {
        return Err(SignalError::InvalidKey {
            reason: format!("AES-256-GCM requires a 32-byte key, got {}", key.len()),
        });
    }

    let cipher = Aes256Gcm::new_from_slice(&key).map_err(|_| SignalError::InvalidKey {
        reason: "failed to construct AES-256-GCM cipher".to_string(),
    })?;

    // Generate 12-byte IV using OS CSPRNG
    let mut iv_bytes = [0u8; 12];
    rand::fill(&mut iv_bytes);
    let nonce = Nonce::from_slice(&iv_bytes);

    // Encrypt with AAD
    let payload = aes_gcm::aead::Payload {
        msg: &plaintext,
        aad: &aad,
    };
    let ciphertext = cipher
        .encrypt(nonce, payload)
        .map_err(|_| SignalError::InternalError {
            reason: "AES-256-GCM encryption failed".to_string(),
        })?;

    Ok(ContentCryptoResult {
        ciphertext,
        iv: iv_bytes.to_vec(),
    })
}

/// AES-256-GCM decrypt with Additional Authenticated Data.
///
/// - Splits `ciphertext` into (encrypted_data, 16-byte auth tag) — the last 16 bytes are the tag.
/// - Verifies the auth tag before returning plaintext (GCM is authenticated).
/// - The `aad` must match the value used during encryption.
///
/// # Errors
///
/// - `InvalidKey` if `key` is not exactly 32 bytes.
/// - `InvalidArgument` if `iv` is not exactly 12 bytes.
/// - `InvalidMessage` if `ciphertext` is too short (< 16 bytes) or auth tag verification fails.
#[uniffi::export]
pub fn aes_gcm_decrypt(
    ciphertext: Vec<u8>,
    iv: Vec<u8>,
    key: Vec<u8>,
    aad: Vec<u8>,
) -> Result<Vec<u8>, SignalError> {
    let key = Zeroizing::new(key);
    if key.len() != 32 {
        return Err(SignalError::InvalidKey {
            reason: format!("AES-256-GCM requires a 32-byte key, got {}", key.len()),
        });
    }

    if iv.len() != 12 {
        return Err(SignalError::InvalidArgument {
            reason: format!("AES-256-GCM requires a 12-byte IV, got {}", iv.len()),
        });
    }

    if ciphertext.len() < 16 {
        return Err(SignalError::InvalidMessage {
            reason: "ciphertext too short — must contain at least 16-byte auth tag".to_string(),
        });
    }

    let cipher = Aes256Gcm::new_from_slice(&key).map_err(|_| SignalError::InvalidKey {
        reason: "failed to construct AES-256-GCM cipher".to_string(),
    })?;

    let nonce = Nonce::from_slice(&iv);

    // aes-gcm expects ciphertext || tag as a single buffer, which is our format
    let payload = aes_gcm::aead::Payload {
        msg: &ciphertext,
        aad: &aad,
    };
    let plaintext = cipher.decrypt(nonce, payload).map_err(|_| {
        // Intentionally opaque error — do not differentiate wrong key / wrong AAD / tampered data
        SignalError::InvalidMessage {
            reason: "decryption failed".to_string(),
        }
    })?;

    Ok(plaintext)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_roundtrip_encrypt_decrypt() {
        let plaintext = b"Hello, Orbital!".to_vec();
        let key = vec![0xAB; 32];
        let aad = b"group-id-123".to_vec();

        let result = aes_gcm_encrypt(plaintext.clone(), key.clone(), aad.clone())
            .expect("encryption should succeed");

        let decrypted = aes_gcm_decrypt(result.ciphertext, result.iv, key, aad)
            .expect("decryption should succeed");

        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_roundtrip_empty_plaintext() {
        let plaintext = vec![];
        let key = vec![0x42; 32];
        let aad = b"g1".to_vec();

        let result =
            aes_gcm_encrypt(plaintext.clone(), key.clone(), aad.clone()).expect("should succeed");

        let decrypted =
            aes_gcm_decrypt(result.ciphertext, result.iv, key, aad).expect("should succeed");

        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_roundtrip_empty_aad() {
        let plaintext = b"no AAD test".to_vec();
        let key = vec![0x11; 32];
        let aad = vec![];

        let result =
            aes_gcm_encrypt(plaintext.clone(), key.clone(), aad.clone()).expect("should succeed");

        let decrypted =
            aes_gcm_decrypt(result.ciphertext, result.iv, key, aad).expect("should succeed");

        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_iv_is_12_bytes() {
        let result =
            aes_gcm_encrypt(b"test".to_vec(), vec![0x00; 32], vec![]).expect("should succeed");
        assert_eq!(result.iv.len(), 12, "IV must be exactly 12 bytes");
    }

    #[test]
    fn test_ciphertext_includes_16_byte_auth_tag() {
        let plaintext = b"tag test".to_vec();
        let result =
            aes_gcm_encrypt(plaintext.clone(), vec![0xFF; 32], vec![]).expect("should succeed");
        assert_eq!(
            result.ciphertext.len(),
            plaintext.len() + 16,
            "ciphertext should be plaintext_len + 16 (auth tag)"
        );
    }

    #[test]
    fn test_decrypt_wrong_key_fails() {
        let plaintext = b"secret".to_vec();
        let key = vec![0xAA; 32];
        let wrong_key = vec![0xBB; 32];
        let aad = b"group".to_vec();

        let result = aes_gcm_encrypt(plaintext, key, aad.clone()).expect("should succeed");

        let err = aes_gcm_decrypt(result.ciphertext, result.iv, wrong_key, aad)
            .expect_err("wrong key should fail");
        assert!(
            matches!(err, SignalError::InvalidMessage { .. }),
            "should be InvalidMessage, got: {err:?}"
        );
    }

    #[test]
    fn test_decrypt_wrong_aad_fails() {
        let plaintext = b"secret".to_vec();
        let key = vec![0xCC; 32];
        let aad = b"group-1".to_vec();
        let wrong_aad = b"group-2".to_vec();

        let result = aes_gcm_encrypt(plaintext, key.clone(), aad).expect("should succeed");

        let err = aes_gcm_decrypt(result.ciphertext, result.iv, key, wrong_aad)
            .expect_err("wrong AAD should fail");
        assert!(matches!(err, SignalError::InvalidMessage { .. }));
    }

    #[test]
    fn test_decrypt_tampered_ciphertext_data_fails() {
        let plaintext = b"tamper test data".to_vec();
        let key = vec![0xDD; 32];
        let aad = b"group".to_vec();

        let result = aes_gcm_encrypt(plaintext, key.clone(), aad.clone()).expect("should succeed");

        // Flip a byte in the encrypted data portion (before the tag)
        let mut tampered = result.ciphertext.clone();
        tampered[0] ^= 0xFF;

        let err = aes_gcm_decrypt(tampered, result.iv, key, aad)
            .expect_err("tampered data should fail");
        assert!(matches!(err, SignalError::InvalidMessage { .. }));
    }

    #[test]
    fn test_decrypt_tampered_auth_tag_fails() {
        let plaintext = b"tamper test tag".to_vec();
        let key = vec![0xEE; 32];
        let aad = b"group".to_vec();

        let result = aes_gcm_encrypt(plaintext, key.clone(), aad.clone()).expect("should succeed");

        // Flip a byte in the auth tag (last 16 bytes)
        let mut tampered = result.ciphertext.clone();
        let tag_start = tampered.len() - 16;
        tampered[tag_start] ^= 0xFF;

        let err = aes_gcm_decrypt(tampered, result.iv, key, aad)
            .expect_err("tampered tag should fail");
        assert!(matches!(err, SignalError::InvalidMessage { .. }));
    }

    #[test]
    fn test_decrypt_wrong_iv_fails() {
        let plaintext = b"IV test".to_vec();
        let key = vec![0x55; 32];
        let aad = b"group".to_vec();

        let result = aes_gcm_encrypt(plaintext, key.clone(), aad.clone()).expect("should succeed");

        let wrong_iv = vec![0x00; 12]; // different IV

        let err = aes_gcm_decrypt(result.ciphertext, wrong_iv, key, aad)
            .expect_err("wrong IV should fail");
        assert!(matches!(err, SignalError::InvalidMessage { .. }));
    }

    #[test]
    fn test_encrypt_wrong_key_length_fails() {
        let err = aes_gcm_encrypt(b"test".to_vec(), vec![0x00; 16], vec![])
            .expect_err("16-byte key should fail");
        assert!(matches!(err, SignalError::InvalidKey { .. }));
    }

    #[test]
    fn test_decrypt_wrong_key_length_fails() {
        let err = aes_gcm_decrypt(vec![0x00; 32], vec![0x00; 12], vec![0x00; 16], vec![])
            .expect_err("16-byte key should fail");
        assert!(matches!(err, SignalError::InvalidKey { .. }));
    }

    #[test]
    fn test_decrypt_wrong_iv_length_fails() {
        let err = aes_gcm_decrypt(vec![0x00; 32], vec![0x00; 16], vec![0x00; 32], vec![])
            .expect_err("16-byte IV should fail");
        assert!(matches!(err, SignalError::InvalidArgument { .. }));
    }

    #[test]
    fn test_decrypt_ciphertext_too_short_fails() {
        let err = aes_gcm_decrypt(vec![0x00; 15], vec![0x00; 12], vec![0x00; 32], vec![])
            .expect_err("ciphertext < 16 bytes should fail");
        assert!(matches!(err, SignalError::InvalidMessage { .. }));
    }

    #[test]
    fn test_unique_ivs_per_encryption() {
        let key = vec![0x77; 32];
        let plaintext = b"same text".to_vec();
        let aad = vec![];

        let r1 =
            aes_gcm_encrypt(plaintext.clone(), key.clone(), aad.clone()).expect("should succeed");
        let r2 = aes_gcm_encrypt(plaintext, key, aad).expect("should succeed");

        assert_ne!(
            r1.iv, r2.iv,
            "IVs must be unique per encryption (CSPRNG)"
        );
    }

    #[test]
    fn test_large_plaintext_roundtrip() {
        // 1 MB plaintext
        let plaintext = vec![0x42; 1_000_000];
        let key = vec![0x99; 32];
        let aad = b"large-group".to_vec();

        let result =
            aes_gcm_encrypt(plaintext.clone(), key.clone(), aad.clone()).expect("should succeed");

        assert_eq!(result.ciphertext.len(), plaintext.len() + 16);

        let decrypted =
            aes_gcm_decrypt(result.ciphertext, result.iv, key, aad).expect("should succeed");

        assert_eq!(decrypted, plaintext);
    }
}
